### ISSUE TITLE
Warning: deprecated feature use (2020-02-01)

### ISSUE THREAD

**Issue by ghost** [tocttou/hacker-blog#11]
Generating... 
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/document.rb:466: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/document.rb:432: warning: Passing the keyword argument as the last hash parameter is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/document.rb:75: warning: The called method `merge_data!' is defined here
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/document.rb:439: warning: Passing the keyword argument as the last hash parameter is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/document.rb:75: warning: The called method `merge_data!' is defined here
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/document.rb:466: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/document.rb:466: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/tags/include.rb:179: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/tags/include.rb:179: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/tags/include.rb:179: warning: Using the last argument as keyword parameters is deprecated
/home/web/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/tags/include.rb:179: warning: Using the last argument as keyword parameters is deprecated

**Comment by tocttou** [comment]
Thanks I'll take a look.

**Comment by ghost** [comment]
When I use Rubu 2.6.5 everything works as expected. So I am happy now. Thanks for this great piece of work!

**Comment by tocttou** [comment]
Fantastic!
