### ISSUE TITLE
Add google analytics

### ISSUE THREAD

**Issue by mzfr** [tocttou/hacker-blog#6]
I am using this theme for my blog. I am planning to add google analytics on it. I've added my google analytic id to my `_config.yml` as mentioned in [configuration-variables](https://github.com/tocttou/hacker-blog/#configuration-variables) section.

Do I need to do anything else like making a new page called `_include/analytic.html` as mentioned in [google-analytics-ghpages.html](https://www.christopherlovell.co.uk/blog/2015/04/13/google-analytics-ghpages.html) or [google-analytics-jekyll/](https://desiredpersona.com/google-analytics-jekyll/) blog post?

**Comment by tocttou** [comment]
No that should be enough.
