### ISSUE TITLE
Display post according to months

### ISSUE THREAD

**Issue by mzfr** [tocttou/hacker-blog#7]
How can I display blog posts according to month and not year?

**Comment by marbodev** [comment]
Hi, you mean first year, later months?
2017 January
2017 February
...
...

**Comment by mzfr** [comment]
Yeah or maybe like

```
2019
	january
		....
2018
	January
		XYZ
		ABC
	Feburary	
		....
```

**Comment by tocttou** [comment]
Thanks for reminding. I'll implement this week.

**Comment by tocttou** [comment]
Anyone willing to pick this up in a PR is welcome!
